# Generated by Django 3.1.6 on 2021-02-14 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('employees', models.PositiveIntegerField()),
                ('theme', models.TextField(help_text='IT/Food/Art etc', max_length=255)),
                ('revenue', models.PositiveIntegerField()),
                ('expected_revenue', models.PositiveIntegerField()),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder', models.CharField(help_text='Name of the bank account owner', max_length=155)),
                ('account_number', models.CharField(max_length=50)),
                ('ifsc_code', models.CharField(max_length=50)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='startup.company')),
            ],
        ),
    ]
